// Auto-generated by scripts/convert-logo.mjs — DO NOT EDIT
// Source: jigepng/pixel_art.html (48x60 pixels → 24x15 terminal using ▀/▄, 4:1 vertical + 2:1 horizontal downsample)

export interface LogoRun {
  readonly text: string;
  readonly fg?: string;
  readonly bg?: string;
}

/** Logo width in terminal columns */
export const STARTUP_LOGO_WIDTH = 48;

/** Logo height in terminal lines */
export const STARTUP_LOGO_HEIGHT = 20;

/** Pre-rendered logo data. 20 lines, each an array of colored runs. */
export const STARTUP_LOGO: readonly (readonly LogoRun[])[] = [
  [
    {
      "text": "                              "
    },
    {
      "text": "▄▄▄▄▄▄",
      "fg": "black"
    },
    {
      "text": "            "
    }
  ],
  [
    {
      "text": "                   "
    },
    {
      "text": "▄▄",
      "fg": "black"
    },
    {
      "text": "▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀▀",
      "fg": "gray",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "green"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▄▄",
      "fg": "black"
    },
    {
      "text": "        "
    }
  ],
  [
    {
      "text": "             "
    },
    {
      "text": "▄",
      "fg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "white"
    },
    {
      "text": "▀▀▀▀▀▀▀▀▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "green"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀▀▀▀▀▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▄",
      "fg": "black"
    },
    {
      "text": "    "
    }
  ],
  [
    {
      "text": "           "
    },
    {
      "text": "▄",
      "fg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "white"
    },
    {
      "text": "▀▀▀▀▀▀▀▀▀▀▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀▀",
      "fg": "green",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀▀▀",
      "fg": "gray",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀▀▀▀▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▄",
      "fg": "black"
    },
    {
      "text": "  "
    }
  ],
  [
    {
      "text": "         "
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "green"
    },
    {
      "text": "▀▀▀▀▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀▀▀▀▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": " "
    }
  ],
  [
    {
      "text": "        "
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "green",
      "bg": "black"
    },
    {
      "text": "▀▀▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀▀▀▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "green",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "green"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "black"
    },
    {
      "text": "▀▀▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀▀",
      "fg": "black",
      "bg": "black"
    }
  ],
  [
    {
      "text": "        "
    },
    {
      "text": "▀",
      "fg": "black"
    },
    {
      "text": "▀▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀▀",
      "fg": "gray",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "green"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "green"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "green"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "green"
    },
    {
      "text": "▀▀",
      "fg": "white",
      "bg": "black"
    },
    {
      "text": "▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black"
    },
    {
      "text": " "
    }
  ],
  [
    {
      "text": "           "
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "green"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "green"
    },
    {
      "text": "▀▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "green",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "green"
    },
    {
      "text": "▀▀▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "green"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "yellow"
    },
    {
      "text": "▀▀▀",
      "fg": "yellow",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "    "
    }
  ],
  [
    {
      "text": "            "
    },
    {
      "text": "▀",
      "fg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "green"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "yellow"
    },
    {
      "text": "▀▀▀▀▀▀",
      "fg": "red",
      "bg": "red"
    },
    {
      "text": "▀▀▀",
      "fg": "yellow",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "green",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "red",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "red"
    },
    {
      "text": "▀▀▀▀▀",
      "fg": "yellow",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "yellow"
    },
    {
      "text": "▀▀▀▀",
      "fg": "red",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "red",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "    "
    }
  ],
  [
    {
      "text": "           "
    },
    {
      "text": "▄",
      "fg": "black"
    },
    {
      "text": "▀▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "red",
      "bg": "yellow"
    },
    {
      "text": "▀▀▀",
      "fg": "red",
      "bg": "red"
    },
    {
      "text": "▀▀",
      "fg": "red",
      "bg": "yellow"
    },
    {
      "text": "▀▀▀▀",
      "fg": "yellow",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "red",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "red",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "black"
    },
    {
      "text": "▀▀▀",
      "fg": "yellow",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "red",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "green",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "red",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "red",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "red",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black"
    },
    {
      "text": "    "
    }
  ],
  [
    {
      "text": "    "
    },
    {
      "text": "▄▄",
      "fg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "red",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "red"
    },
    {
      "text": "▀▀▀▀▀▀▀▀▀▀▀▀▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "green",
      "bg": "black"
    },
    {
      "text": "▀▀",
      "fg": "gray",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "green"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀▀",
      "fg": "yellow",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "green"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "black"
    },
    {
      "text": "▀▀",
      "fg": "green",
      "bg": "black"
    },
    {
      "text": "▀▀▀▀▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "    "
    }
  ],
  [
    {
      "text": "   "
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀▀",
      "fg": "black",
      "bg": "red"
    },
    {
      "text": "▀▀▀▀",
      "fg": "red",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "red"
    },
    {
      "text": "▀▀",
      "fg": "red",
      "bg": "red"
    },
    {
      "text": "▀▀▀▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "green"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "green"
    },
    {
      "text": "▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▄",
      "fg": "black"
    },
    {
      "text": "    "
    }
  ],
  [
    {
      "text": " "
    },
    {
      "text": "▄",
      "fg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀▀",
      "fg": "red",
      "bg": "red"
    },
    {
      "text": "▀▀",
      "fg": "red",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "red",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "red",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "red",
      "bg": "black"
    },
    {
      "text": "▀▀▀▀▀▀▀▀▀▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "green"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀▀▀▀▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "green",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "green"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀▀▀▀▀▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▄",
      "fg": "black"
    },
    {
      "text": "  "
    }
  ],
  [
    {
      "text": " "
    },
    {
      "text": "▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀▀▀▀",
      "fg": "red",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "red",
      "bg": "red"
    },
    {
      "text": "▀▀▀▀▀▀▀▀▀▀▀▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀▀▀▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀▀",
      "fg": "gray",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "white"
    },
    {
      "text": "▀▀▀▀▀▀▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "  "
    }
  ],
  [
    {
      "text": "  "
    },
    {
      "text": "▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀▀▀▀▀",
      "fg": "red",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀▀",
      "fg": "gray",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "green"
    },
    {
      "text": "▀▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "green",
      "bg": "gray"
    },
    {
      "text": "▀▀▀▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "green",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀▀▀▀",
      "fg": "black",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "green",
      "bg": "gray"
    },
    {
      "text": "▀▀▀▀",
      "fg": "black",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "green",
      "bg": "black"
    },
    {
      "text": "▀▀",
      "fg": "gray",
      "bg": "green"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "magenta"
    },
    {
      "text": "  "
    }
  ],
  [
    {
      "text": "   "
    },
    {
      "text": "▀",
      "fg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "red",
      "bg": "black"
    },
    {
      "text": "▀▀▀",
      "fg": "red",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "black"
    },
    {
      "text": "▀▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "black"
    },
    {
      "text": "▀▀▀▀▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "green"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀▀▀▀▀▀▀▀",
      "fg": "green",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "green"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "   "
    }
  ],
  [
    {
      "text": "             "
    },
    {
      "text": "▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀▀▀▀▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀▀▀▀▀▀▀▀▀▀▀▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀▀",
      "fg": "gray",
      "bg": "gray"
    },
    {
      "text": "▀▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black"
    },
    {
      "text": "       "
    }
  ],
  [
    {
      "text": "              "
    },
    {
      "text": "▀",
      "fg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "white",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "yellow"
    },
    {
      "text": "▀▀",
      "fg": "yellow",
      "bg": "white"
    },
    {
      "text": "▀▀▀",
      "fg": "gray",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "green",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "green",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "green",
      "bg": "green"
    },
    {
      "text": "▀",
      "fg": "green",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "green",
      "bg": "yellow"
    },
    {
      "text": "▀▀▀",
      "fg": "gray",
      "bg": "white"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "white"
    },
    {
      "text": "▀▀",
      "fg": "yellow",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "green",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black"
    },
    {
      "text": "         "
    }
  ],
  [
    {
      "text": "                "
    },
    {
      "text": "▄",
      "fg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "yellow"
    },
    {
      "text": "▀▀▀",
      "fg": "yellow",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▄",
      "fg": "black"
    },
    {
      "text": "     "
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "gray",
      "bg": "yellow"
    },
    {
      "text": "▀▀▀",
      "fg": "yellow",
      "bg": "yellow"
    },
    {
      "text": "▀▀",
      "fg": "black",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "red"
    },
    {
      "text": "▄",
      "fg": "black"
    },
    {
      "text": "         "
    }
  ],
  [
    {
      "text": "               "
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "blue"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "gray"
    },
    {
      "text": "▀▀",
      "fg": "yellow",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "gray"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "yellow"
    },
    {
      "text": "▀",
      "fg": "red",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "     "
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "red",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "red"
    },
    {
      "text": "▀",
      "fg": "red",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "yellow",
      "bg": "red"
    },
    {
      "text": "▀▀",
      "fg": "red",
      "bg": "black"
    },
    {
      "text": "▀",
      "fg": "black",
      "bg": "black"
    },
    {
      "text": "         "
    }
  ]
] as const;
